import "./globals.css";

import type {Metadata} from "next";
import { Inter as FontSans } from "next/font/google"
import Navbar from "@/app/_components/navbar"
import {cn} from "@/lib/utils";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
    title: "Issue Tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body
            className={cn(
                "min-h-screen bg-background font-sans antialiased",
                fontSans.variable
            )}
        >
            <Navbar/>
            <main className={"max-w-7xl mx-auto p-5"}>{children}</main>
        </body>
        </html>
    );
}
