import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Navbar from "@/app/_components/navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Issue Tracker',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Navbar/>
        <main className={'max-w-7xl mx-auto'}>
            {children}
        </main>
        </body>
        </html>
    )
}
